name: Test GH_PAT Secret

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debugging PAT
      run: |
        echo "Token length: ${#GH_PAT}"
        echo $(echo -n "$GH_PAT" | sha256sum)
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
