name: Test GH_PAT Secret

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print hashed GH_PAT
      run: echo "${{ secrets.GH_PAT }}"